//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Access_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarsModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarsModel()
        {
            this.CarFleets = new HashSet<CarFleet>();
        }
    
        public int CarModelID { get; set; }
        public int ManufacturerID { get; set; }
        public string CarModel { get; set; }
        public int ManufactureYear { get; set; }
        public string Transmission { get; set; }
        public decimal DailyRate { get; set; }
        public decimal LateFee { get; set; }
        public bool IsDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarFleet> CarFleets { get; set; }
        public virtual Manufacture Manufacture { get; set; }
    }
}
